const data = {
  a: "audio/steve-1.m4a",
  s: "audio/sam-1.m4a",
  d: "audio/monik-1.m4a",
  f: "audio/megan-1.m4a",
  g: "audio/lydia-1.m4a",
  h: "audio/lexi-1.m4a",
  j: "audio/jason-1.m4a",
  k: "audio/eden-1.m4a",
  l: "audio/alex-1.m4a",
  q: "audio/stephen-1.m4a",
  w: "audio/sam-2.m4a",
  e: "audio/monik-2.m4a",
  r: "audio/megan-2.m4a",
  t: "audio/lydia-2.m4a",
  y: "audio/lexi-2.m4a",
  u: "audio/eden-2.m4a",
  i: "audio/steve-2.m4a",
  o: "audio/stephen-2.m4a",
  p: "audio/megan-3.m4a",
  x: "audio/lydia-3.m4a",
  c: "audio/eden-3.m4a",
  v: "audio/steve-3.m4a",
  z: "audio/stephen-3.m4a",
};
